### ISSUE TITLE
Setting Listener

### ISSUE THREAD

**Issue by bwong199** [omaflak/Bluetooth-Terminal#1]
Hi, 

How do you set a listener to listen for data received? 

Thanks.

**Comment by omaraflak** [comment]
Hi, 

Everything is in Bluetooth Library. The project is in my repo. It's a one file library, you should find the answer to your question easily ;)

Regards

**Comment by omaraflak** [comment]
https://github.com/omaflak/Bluetooth-Library/blob/master/bluetooth/src/main/java/me/aflak/bluetooth/Bluetooth.java

**Comment by HariHend1973** [comment]
hi, i've just found your library :). i'm also wonder if you can provide example how to handle received data. i've created echo server using python, and build your  bluetooth terminal.it works  flawlessly. but i didn't know how to get/handle data echoed by server. i'm trying with another bluetooth terminal provided by playstore. my python server replied.
 thanks in advanced. overall your library is working good.

i'm using me.aflak.libraries:bluetooth:1.2.4

**Comment by omaraflak** [comment]
Hi @HariHend1973, this is actually not the code for the library. This is the one, checkout the README as it contains a lot of useful information :

https://github.com/OmarAflak/Bluetooth-Library

The latest version is `1.3.9` :

```
implementation 'me.aflak.libraries:bluetooth:1.3.9'
```

What do you mean exactly by :

> example how to handle received data

?

**Comment by HariHend1973** [comment]
thanks for the quick response, actually your library is working properly when sending data to other device. what i'm asking when other device replying, the app doesn't receive any data.

is the response supposed to be here?

```
    @Override
    public void onMessage(String message) {
        Display(name+": "+message);
    }
```
i got example bluetooth terminal from here https://github.com/OmarAflak/Bluetooth-Terminal

if i change the version to 1.3.9 i'll get lots of error in java classes

**Comment by omaraflak** [comment]
Oh yes it is supposed to be there. But be careful, you need to append a new line character `\n` at the end of your message (server side) if you want the callback to be triggered.

You can override this behavior with the new version.

**Comment by HariHend1973** [comment]
i think Display method already handle that

```
    public void Display(final String s){
        this.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                text.append(s + "\n");
                scrollView.fullScroll(View.FOCUS_DOWN);
            }
        });
    }
```

but still no data received from other pair/device :(

**Comment by omaraflak** [comment]
No that's not what I mean. I mean when you're sending the message from the **server**, add `\n` at the end of the message.

**Comment by HariHend1973** [comment]
> No that's not what I mean. I mean when you're sending the message from the **server**, add `\n` at the end of the message.

owhh, i'll try append '\n' on server reply. thanks alot :)

**Comment by HariHend1973** [comment]
@OmarAflak thank you very much, it works. i'll try latest library version tomorrow :)
