### ISSUE TITLE
Failure to connect and chat between two android phones

### ISSUE THREAD

**Issue by mjohn123** [omaflak/Bluetooth-Terminal#2]
Thank you for great API and app. I tried to use your app. to connect two android phones. However, it cannot connect and create a socket for chatting. How do I need modify to chat between two android phones?

**Comment by omaraflak** [comment]
Hi, I'm glad if it can help. Unfortunately when I made the app (and the library) it was for the HC-06 bluetooth module. It wasn't destined to be used between two phones... However you have an example provided by Google if you still want to make a bluetooth chat: https://android.googlesource.com/platform/development/+/25b6aed7b2e01ce7bdc0dfa1a79eaf009ad178fe/samples/BluetoothChat

Good luck with that ;)

**Comment by omaraflak** [comment]
PS: I'll try to change the library to support this functionality

**Comment by mjohn123** [comment]
Thank you. One more thing, could you make it as service app because we have to receive the data whenever the phone is sleep or press home button. The importance thing is that maintain the connection when the phone is sleep or the back button is press. If it is possible, I think you app can be similar the chat app as Skype, Kakaotalk, FB Mess, so on

**Comment by mjohn123** [comment]
Hello Omaflak. I was successful connect two android phones. Your code can be used as client side. Hence, I used sample bluetooth chat for server side. Your code can send data but it cannot receive data. Could you check it?

![kakaotalk_20160814_175453440](https://cloud.githubusercontent.com/assets/10252224/17648241/b9407134-6248-11e6-8a83-a98f8169b6da.jpg)

**Comment by omaraflak** [comment]
The client is reading with `readLine(`) which means each message has to end with a "\n"
(I think I found you on stackoverflow)

**Comment by mjohn123** [comment]
Thank you. Good job. I got it. I am testing your code when we press the back button. It looks to kill the application but the socket does not close. Can we make your lib as a service to receive a message when the phone is sleep? It is similar skype, Whatsapp...

**Comment by omaraflak** [comment]
I suppose you can. Create a new service and use the lib inside of it.
PS: you have to call `disconnect()` if you want the socket
