### ISSUE TITLE
Resume to chat after backing

### ISSUE THREAD

**Issue by neilyo94** [omaflak/Bluetooth-Terminal#4]
Hello, thanks for the source code. My questions is how to resume to chat after backing? I use your source code as a sub-activity(not main activity), and I wish I can still able to go back to the chat history instead of creating a new intent (which the first bluetooth thread is running in the background tho which is great). 

Any experience of this on your part?

**Comment by omaraflak** [comment]
Hey! I haven't worked on this code for a long time. And honnestly the code is pretty awful... I only made the app to make some quick test with electronics. Not sure I can answer your question, but you can implement the chat yourself pretty easily using the same library I used : [https://github.com/omaflak/Bluetooth-Library](https://github.com/omaflak/Bluetooth-Library)

Hope it will help
